### ISSUE TITLE
Access object of each inline within template of baton_form_includes

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#80] opened 2020-07-09 04:09 UTC
I really like the new Form Includes feature, but i notice it only work with normal field ModelAdmin

Is there anyway to use it with  admin Inline ? and the `{{original}}` in the template will be each object of the inline 
Thank for reading :)

**Comment by linhnvhicts** [comment] 2020-07-09 04:19
oh i found out, instead of using `baton_form_includes`, i can use in ModelAdmin of the main object like normal and use inline fields

Still can't figure how to access the object of each inline object in template :(

**Comment by abidibo** [comment] 2020-07-10 10:18
Hi @linhnvhicts ,

I think I've not understood properly what you're trying to achieve, can you please elaborate more and add an example, thanks

**Comment by linhnvhicts** [comment] 2020-07-12 04:16
I know from the document that i can access object in  the change form from {{ original }}. So if i use an inline field in django baton form include , how do i access each inline object ?

**Comment by abidibo** [comment] 2020-07-21 14:09
@linhnvhicts I see,

short answer: you can't.

The includes are managed as js templates places at the end of the `change_form.html` template. So they can access the context of the change_form template, but cannot access the internal context inside the inline. I mean, you can access the `{{ original }}` inlines, but you cannot access any single inline in its position because the template is just one and rendered one time, then copied multiple times if needed:

``` html
<p>
{% with original.videos.first as v %}
Just a test {{ v.code }}
{% endwith %}
</p>
```

you can do such thing, but then in all inlines you'll see the first video code, you cannot access sequentially all the codes.

Quite tough to explain, I hope you can understand

**Comment by abidibo** [comment] 2020-07-21 14:13
I'm closing for now, because not a bug but an enhancement that probably will not be included soon in a release, because I can't see a way to implement it without overriding too much stuff, and I don't want to

**Closed by abidibo** 2020-07-21 14:13 UTC
Labels: enhancement, more info needed
