### ISSUE TITLE
view problem

### ISSUE THREAD

**Issue by mahapatra-arup** [otto-torino/django-baton#33] opened 2019-12-28 15:21 UTC
You don't have permission to view or edit anything.

**Comment by abidibo** [comment] 2020-01-02 13:32
Hi,
you should definetely provide more info about what exactly the problem is, your environment, log messages, screenshots and so on...

**Comment by abidibo** [comment] 2020-01-13 09:35
I'm closing this since no additional information was provided

**Closed by abidibo** 2020-01-13 09:35 UTC
