### ISSUE TITLE
Inline tabs broken on update to django 3.1

### ISSUE THREAD

**Issue by simonwiles** [otto-torino/django-baton#89] opened 2020-08-19 00:29 UTC
On updating to `django==3.1` today, and inline form tabs are broken -- I can change from the default tab to a second tab, but not back again.  I've tried with `django-baton==1.9.2` and `django-baton==1.10.8`, and have the same problem in either case.  Both of these versions work just fine with `django==3.0.9`.

Any idea what might be up?

**Comment by Flewerty** [comment] 2020-08-24 09:59
Same issue.
That is because of duplicate of div with ids "main".
In Django 3.1 in admin templates in base.html div tag with "main" is already exist:
`<div class="main shifted" id="main">`

So I think it's need to be renamed in next commit: first default tab to something another not "main" id name.

For me the fast solution without changing of module that is overwriting of Baton template base_site.html with this ids rename JS code:
```
        (function ($, undefined) {
            $(window).on('load', function () {
                Baton.Dispatcher.register('onReady', function () { 
                    $('a[href="#main"]').attr('href', '#main-tab')
                    $("div#main.tab-pane").attr("id","main-tab");
                 })
                Baton.init({
                    api: {
                        app_list: '{% url 'baton-app-list-json' %}',
                        gravatar: '{% url 'baton-gravatar-json' %}'
                    },
                    confirmUnsavedChanges: {{ confirm_unsaved_changes|yesno:"true,false" }},
                    showMultipartUploading: {{ show_multipart_uploading|yesno:"true,false" }},
                    enableImagesPreview: {{ enable_images_preview|yesno:"true,false" }},
                    changelistFiltersInModal: {{ changelist_filters_in_modal|yesno:"true,false" }},
                    menuAlwaysCollapsed: {{ menu_always_collapsed|yesno:"true,false" }},
                    menuTitle: '{{ menu_title|escapejs }}',
                    gravatarDefaultImg: '{{ gravatar_default_img }}'
                });
            })
        })(jQuery, und
```efined)
    </script>

**Comment by simonwiles** [comment] 2020-08-25 04:54
Yep, that's it, thanks for uncovering that.  I've raised PR #90 to address the problem.

**Comment by abidibo** [comment] 2020-08-30 08:25
Ok guys, thanks. I'll merge it next week

**Closed** 2020-08-31 07:48 UTC
