### ISSUE TITLE
User drop-down  menu items problem

### ISSUE THREAD

**Issue by teethgrinder** [otto-torino/django-baton#14] opened 2019-04-19 10:13 UTC
Hello,

User Dropdown menu items stays behind the admin panel in my case. How can I fix this ? the menu items under "Ytsejam" are not shown in the image.
![Screenshot from 2019-04-19 13-10-03](https://user-images.githubusercontent.com/713918/56419980-e523d480-62a4-11e9-894b-557a2e8fe1c7.png)

Thanks for your app , it looks promising.

**Comment by abidibo** [comment] 2019-04-19 10:36
Thanks, I'll look into it soon, can you provide some more info in the meanwhile, like os and browser version? Thanks.

**Comment by teethgrinder** [comment] 2019-04-19 10:42
of course. I use Arch linux( every arch user declares that they use arch linux - traditions ) 
and Chromium Version 73.0.3683.103 (Official Build) Arch Linux (64-bit). I
I checked the problem in Firefox after your question, issue is on Chromium only. Firefox handless css correctly.

**Comment by abidibo** [comment] 2019-04-21 08:43
I'm unable to reproduce this bug. I have no problems with google chrome and chromium, build 73.0.3683.86 on ubuntu, and I can't install version 73.0.3683.103 for unmet dependencies. I'll check my chromium version after next upgrade to see if I can reproduce the problem.

It seems like the z-index property of the dropdown element is ignored in some way. It's impossible to debug this stuff without reproducing it and inspecting elements in the browser. I keep it open, let me know if future builds of chromium fix this issue, it may also be a browser bug.

**Comment by teethgrinder** [comment] 2019-04-21 08:50
My user had the same problem in windows 10 and firefox. I think also it is about "z-index" but inner part under this menu stays on top.

**Comment by teethgrinder** [comment] 2019-04-21 09:02
Found problem source it is in base.css line 830
```
#header {
    width: auto;
    height: auto;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 40px;
    background: #417690;
    color: #ffc;
    /* overflow: hidden; */
}
```

I commented overflow:hidden and there is no problem.

**Comment by abidibo** [comment] 2019-04-21 09:44
OK, the strange thing is that baton resets completely the base.css file in order to avoid such things. Your base.css adimn file shoul contain (https://github.com/otto-torino/django-baton/blob/master/baton/static/admin/css/base.css):

`/* empty */`

Maybe you've not inserted `baton` in installed apps before `django.contrib.admin`?

With a normal installation I don't have such roles for the #header element as you posted.

**Comment by abidibo** [comment] 2019-04-24 10:33
Hi @teethgrinder ,
any news on this one? Have you understood why your base.css is not reset? In a normal installation you shouldn't have the overflow hidden rule, let me know since I'd like to close this issue, thanks

**Comment by teethgrinder** [comment] 2019-04-24 11:11
All the applications are correct in  line,
`INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
   ...
    'yogavidya.apps.articles',
     'baton.autodiscover',
]`
and my urls:
`from baton.autodiscover import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),]`

my best guess cant collect the baton css files overwriting admin.css .

**Comment by abidibo** [comment] 2019-04-26 15:23
Not sure, django will get the first base.css file it finds following the INSTALLED_APPS applications order. 
maybe the output of the `collecstatic` command can say something about what is happening.

**Comment by teethgrinder** [comment] 2019-04-26 16:08
I deleted my `static_cdn` folder. collected them all, still same results. trying to figure out where the confusion comes from. I will inform you after trying everything.

**Comment by abidibo** [comment] 2019-05-13 15:29
I'm closing this since I've not received any more feedback, and it doesn't sound like a baton problem. Feel free to reopen if needed.

**Closed by abidibo** 2019-05-13 15:29 UTC
