### ISSUE TITLE
Menu not showing in Django 2

### ISSUE THREAD

**Issue by farooqaaa** [otto-torino/django-baton#46] opened 2020-05-05 19:57 UTC
If you use Baton's `admin.site.urls` in _urls.py_, the menu doesn't show. This can be fixed by using Django's admin URLs. I think this should be mentioned in the docs.

**Comment by abidibo** [comment] 2020-05-11 14:44
It's not clear to me, can you elaborate more please?

**Comment by abidibo** [comment] 2020-06-12 07:55
I'm closing this for now, not a bug and the application works as expected when following the installation instructions

**Closed by abidibo** 2020-06-12 07:55 UTC
