### ISSUE TITLE
admin base.css is still loading messing up the baton design 

### ISSUE THREAD

**Issue by shashitechno** [otto-torino/django-baton#164] opened 2021-05-27 17:54 UTC
hey guys, 

I installed the module and with in admin dashboard its still loading the admin/css/base.css which messed up the dashboard design ( making fonts white etc ? )

Any hints what causing this?

**Comment by jeanwainer** [comment] 2021-05-29 04:39
Are you using django 3.2? It seems that Baton is not yet prepared to work with the new django version. It would be nice to hear from the maintainers if there's any work being done in that direction.

**Comment by abidibo** [comment] 2021-05-29 06:55
Hi guys, 
yes I've already done some job in the develop branch.
https://github.com/otto-torino/django-baton/commit/9905c2d079001eb70d18381c8e8bcd9aa97e15e0
I'll add some more work and release soon, stay tuned

**Comment by jeanwainer** [comment] 2021-05-29 07:08
Awesome, @abidibo! Thank you!

**Comment by abidibo** [comment] 2021-05-31 15:35
Hi @shashitechno ,

actually I cannot reproduce the problem. The `base.css` file

![Screenshot from 2021-05-31 17-30-46](https://user-images.githubusercontent.com/444093/120215487-161db400-c236-11eb-92c9-ce52c58db661.png)

is overridden by Baton, and includes nothing (in current Baton 2.1.5) or some variable definitions (develop branch). If the default Django base CSS is loaded instead, it should have something to do with resolution order, and maybe INSTALLED APPS settings.

Can you provide more information, like your settings.py?

**Comment by abidibo** [comment] 2021-05-31 15:37
@jeanwainer 
can you try the develop branch? It seems to work just well for me with `Django==3.2.3`

**Comment by shashitechno** [comment] 2021-05-31 15:49
I figured it out it - base.css was overided via assets folder.

This can be closed

**Comment by abidibo** [comment] 2021-05-31 16:44
@jeanwainer ,

the develop branch should not work well with Django 3.2, can you give it a try?

**Comment by MathiasKowoll** [comment] 2021-05-31 17:49
I used with develop with Django 3.2 and no issues.

**Comment by jeanwainer** [comment] 2021-05-31 22:29
using develop branch and django 3.2.3 it still doesnt work for me. The left menu goes away.
I get this on console:
`Failed to load resource: the server responded with a status of 404 (Not Found): http://127.0.0.1:8000/baton/app-list-json/`

**Comment by abidibo** [comment] 2021-06-01 07:22
@jeanwainer that's really strange. And the same installation works with django < 3.2.x? It seems like a missing URL entry for me

**Comment by abidibo** [comment] 2021-06-07 10:10
@jeanwainer any news on this one? If not, I'm going to close it

**Comment by jeanwainer** [comment] 2021-06-07 13:47
Hey @abidibo. Yes, the same installation works when I downgrade django to any version below 3.2.

**Comment by abidibo** [comment] 2021-06-16 12:18
I cannot reproduce this bug. Can you set up a repo which reproduces the issue?

**Comment by MathiasKowoll** [comment] 2021-06-17 02:56
I'm also with Django 3.2.4 without any issues.

**Comment by abidibo** [comment] 2021-08-03 12:41
I'm closing this because of lack of activity and no repo provided which reproduces the issue, an issue that I cannot replicate.
Feel free to re-open in case you provide more info.

**Closed by abidibo** 2021-08-03 12:41 UTC
Labels: more info needed, under review
